# Generated by Django 5.2.8 on 2025-11-06 21:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=128)),
                ('user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('system_prompt', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('event', 'Event')], max_length=16)),
                ('text', models.TextField(blank=True)),
                ('event', models.CharField(blank=True, max_length=64)),
                ('is_final', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='conversation.session')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
